name: Web Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2
          cache-cleanup: never
          cache-overwrite-existing: true
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Upgrade YarnLock
        run: ./gradlew kotlinUpgradeYarnLock

      - name: Build JS Browser Distribution
        run: ./gradlew jsBrowserDistribution
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./composeApp/build/dist/js/productionExecutable

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=ailingo-app

      - name: Deployment summary
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL >> $GITHUB_STEP_SUMMARY
                  
